### ISSUE TITLE
Open a direct fork on reinvent_models since it's available

### ISSUE THREAD

**Issue by drugilsberg** [GT4SD/gt4sd-core#113]
Instead of using https://github.com/GT4SD/reinvent_models (tracked contribution here https://github.com/MolecularAI/Reinvent/issues/41).
We should directly open the fork on the public repo: https://github.com/MolecularAI/reinvent-models (most likely not available at the time we went live)

Involving @Ashish13898 mostly for feedback on what is needed to implement this.

**Comment by drugilsberg** [comment]
here a PR: https://github.com/MolecularAI/reinvent-models/pull/1

**Comment by jannisborn** [comment]
Closed. For discussion see https://github.com/MolecularAI/reinvent-models/pull/1 and https://github.com/MolecularAI/Reinvent/issues/41
