### ISSUE TITLE
Handle artifacts for property predictors

### ISSUE THREAD

**Issue by drugilsberg** [GT4SD/gt4sd-core#116]
**Is your feature request related to a problem? Please describe.**
Currently we excluded some property predictors because they have complex logics or they rely on artifacts (e.g., toxicity)

**Describe the solution you'd like**
We should make those available, most likely relying on S3 syncing, we can have a separate bucket for those.

**Comment by jannisborn** [comment]
Once I complete this, we can move on with #115
