### ISSUE TITLE
Unify scores and property predictors

### ISSUE THREAD

**Issue by drugilsberg** [GT4SD/gt4sd-core#118]
**Is your feature request related to a problem? Please describe.**
Unifying `gt4sd.domains.materials` scorers and `gt4sd.properties` seems like a natural step.

**Describe alternatives you've considered**
A good starting point can be to `gt4sd.properties` in `gt4sd.domains.materials` to define a scorer based on those.

**Comment by georgosgeorgos** [comment]
* Use scores based on property_prediction to define rewards for tasks
