### ISSUE TITLE
RT sampling_wrapper to specify a substructure or series of tokens to keep unmasked 

### ISSUE THREAD

**Issue by OleinikovasV** [GT4SD/gt4sd-core#139]
I would like to propose an upgrade on the feature demonstrated in this notebook:
https://github.com/GT4SD/gt4sd-core/blob/main/notebooks/regression-transformer-demo.ipynb (see cells 12-14)

In addition to explicitly specifying tokens_to_mask, one probably could more likely imagine that a chemist might want to specify a substructure to mask or to "freeze" (keep unchanged, i.e. unmasked). It might be easier to specify tokens to freeze as that would be just selecting a part of the string to be kept unmasked. Prototype example is given below.

```
    sampling_wrapper={
        'property_goal': {
            '<logp>': 6.123,
            '<scs>': 1.5
        },
        'fraction_to_mask': 0.6,
        # keep morpholino tail unchanged
        'tokens_to_freeze': ['N4CCOCC4']
    }
```
If one could specify substructure to freeze or to mask - that would be potentially even more advantageous, as that would remove ambiguities when a substructure can be expressed in more than one sequence.

```
    sampling_wrapper={
        'property_goal': {
            '<logp>': 6.123,
            '<scs>': 1.5
        },
        'fraction_to_mask': 0.6,
        # keep morpholino tail unchanged
        'substructure_to_freeze': ['N1CCOCC1'],
        # explicitly mask benzene ring moiety
        'substructure_to_mask':  ['C1=CC=CC=C1'],
    }
```

One could use RDKit functionality to identify substructure tokens, as given here: https://www.rdkit.org/docs/Cookbook.html#substructure-matching

Regarding the interpretation of the 'fraction_to_mask', I would then imagine that it would best applied to the remaining set of tokens (after tokens_to_freeze and explicit tokens_to_mask are excluded).
I hope this makes sense, happy to clarify and exemplify further.

**Comment by drugilsberg** [comment]
Hey @OleinikovasV thanks a lot for the suggestion and the details, it looks super clear, we will open a PR and add you as reviewer to get some feedback as soon as we have an implementation available.

**Comment by jannisborn** [comment]
Hi @OleinikovasV,
Thanks for the suggestion this should be possible.
But under the hood the model works with SELFIES (not SMILES).
The easy solution would be to convert these substructures to SELFIES and then perform the match in the two SELFIES sequences (i.e., not with RDKit). I think this would be the best approach for a prototype. The alternative would be to try tracking which SMILES tokens are converted to SELFIES. This is also [possible](https://github.com/aspuru-guzik-group/selfies/pull/84) but requires a bit more work.

I'm happy to guide you through implementing this prototype. It can b readily combined with the `fraction_to_mask` parameter. 

I believe the right entry point for this PR would be here: https://github.com/GT4SD/gt4sd-core/blob/main/src/gt4sd/algorithms/conditional_generation/regression_transformer/implementation.py#L612

To freeze a substructure one could convert to SELFIES, identify which tokens have to be masked and track this with a binary "protection" vector. Then the existing masking could be performed and afterwards the `substructure_to_mask` could be converted to SELFIES and if any of those tokens are still unmasked, they could be masked a posteriori

**Comment by drugilsberg** [comment]
Thanks for the input @jannisborn, we can discuss how to implement it via the quick conversion, I think it could be a great first version.

**Comment by jannisborn** [comment]
Hi @OleinikovasV,

I provided code to support the requested feature in #163 
Please feel free to have a look!
