### ISSUE TITLE
GT4SD trainer is not compatible with the latest versions of transformers

### ISSUE THREAD

**Issue by christofid** [GT4SD/gt4sd-core#147]
In version 4.22.0 of transformers, the option to HfArgumentParser.parse_{dict,json_file} to raise an Exception when there are extra keys has been added. The default option to raise such Exception create issues to our parse as we always use extra keys.

**Comment by georgosgeorgos** [comment]
And `diffusers` relies on the last version of transformers.

**Comment by christofid** [comment]
Addressed by #148
