### ISSUE TITLE
RT: gt4sd-trainer pipeline falls back to HF hub when the starting model is not in the local cache

### ISSUE THREAD

**Issue by drugilsberg** [GT4SD/gt4sd-core#156]
**Describe the bug**

When running `gt4sd-trainer` using a starting model not present in the local cache, there is fallback mechanism to look for the model in the HF hub.

**To Reproduce**
1. Install gt4sd or simply use the base docker image
2. Run the example for RT training

**Expected behavior**
The command should trigger a sync of the remote cache.

**Comment by jannisborn** [comment]
Should be solved via #157
