### ISSUE TITLE
pretrained models

### ISSUE THREAD

**Issue by davidegraff** [GT4SD/gt4sd-core#177]
Forgive a potentially dumb question, but are pretrained models available in GT4SD? I'm looking to evaluate a bunch of generative models, and was hoping to not have to deal with training them all myself. Thanks!

**Comment by drugilsberg** [comment]
There are around 26 models already available that should be downloaded automatically when running inference.
I recommend checking out the example notebooks where you can see how to access them directly.
In this one for example we show how to access around 10 of them: https://github.com/GT4SD/gt4sd-core/blob/main/notebooks/discovery-demo.ipynb.

**Comment by davidegraff** [comment]
oh wonderful- thanks for the help!
