### ISSUE TITLE
weights.pkl file missing

### ISSUE THREAD

**Issue by palazzef** [GT4SD/gt4sd-core#180]
**Describe the bug**
Hi, 

Thanks for the nice project!

Today I tried to run the discovery-demo notebook and by running line 15 of the "First attempt" block I got the following error:

 No such file or directory: '/home/myaccountname/.gt4sd/algorithms/generation/TorchDrugGenerator/TorchDrugGCPN/zinc250k_v0/weights.pkl'

I tried also different models, and I got similar errors for VAE and AAE:
FileNotFoundError: [Errno 2] No such file or directory: '/home/myaccountname/.gt4sd/algorithms/conditional_generation/MosesGenerator/AaeGenerator/v0/config.pt'
FileNotFoundError: [Errno 2] No such file or directory: '/home/myaccountname/.gt4sd/algorithms/conditional_generation/MosesGenerator/VaeGenerator/v0/config.pt'

I reported as a 'bug' but maybe it is my fault in installing/piping the pkgs.

(I followed the README instructions of the main page and also of the notebook page.)

**To Reproduce**
Run the discovery-demo notebook present in the notebook folder.

**Expected behavior**
I was expecting to reproduce the provided results in the discovery-demo notebook

**System (please complete the following information):**
 - OS: ubuntu/HPC cluster 
 - Python version: 3.8.15

**Comment by drugilsberg** [comment]
Thanks @palazzef, we will surely investigate this and will let you know as soon as we have news.

**Comment by jannisborn** [comment]
Hi @palazzef,
to me this looks like a problem with syncing the models from the COS to your local cache. Can you confirm that paths like `/home/myaccountname/.gt4sd/algorithms/generation/` exist and that you see the model artifacts in the subfolder. The error message suggests that this is not the case. 

Maybe you do not have permission to create/write to this directory or you're out of disk space (you mentioned you're running this on HPC).

Normally, whenever you're running a model for the first time, it gets synced to your local cache. We havent had issues with this in the past.

**Comment by palazzef** [comment]
Hi,

Thanks for the super prompt reply.

Yes, I can confirm you that I have this folder, but you are right about the out-of-disk problem. On this folder I am allowed to have only up to 4G space - and now only 1G is left. Are the missing files bigger than this?

Could I re-direct those files/models to another folder?

Thanks!

**Comment by jannisborn** [comment]
Sure, I indeed recommend redirecting. You can do that by:
```sh
 export GT4SD_LOCAL_CACHE_PATH="your_desired_path"
```
before starting the notebook. Or you just do `os.environ` inside the notebook (before you import anything gt4sd related). 
Hope this helps, let us know otherwise

**Comment by palazzef** [comment]
Hi @jannisborn 
Thanks for the suggestion, but it didn't work.

After the export (export GT4SD_LOCAL_CACHE_PATH=/data/users/myaccount_withsomesubfolders/pkgs/), I rerun everything and while the CACHE folder is now correctly changed, the error is still the same:

No such file or directory: '/data/users/myaccount_withsomesubfolders/pkgs/algorithms/generation/TorchDrugGenerator/TorchDrugGCPN/zinc250k_v0/weights.pkl'

Once again the folders are there but empty:

ls pkgs/algorithms/generation/TorchDrugGenerator/TorchDrugG*/zin*
pkgs/algorithms/generation/TorchDrugGenerator/TorchDrugGCPN/zinc250k_v0:

pkgs/algorithms/generation/TorchDrugGenerator/TorchDrugGraphAF/zinc250k_v0:

On /data/ folder I shouldn't have out of space problem, because I have more than 12T available. 

Thanks.

**Comment by jannisborn** [comment]
I'm sorry to hear this @palazzef. I'm not able to replicate this problem locally. Are you sure that you dont have a network/connection issue? 

My first guess from here would be that the syncing is triggered successfully, hence the folders are being created. But then, when the actual content is being downloaded, the connection breaks (or is too slow) and so the files never arrive in the location.

**Comment by palazzef** [comment]
Thanks for the comment. 

Is there a way to download those files "manually" and then add to those folders?

**Comment by jannisborn** [comment]
You could run the code locally and then `scp` the created folders to your HPC. Let us know if this does not work for you.

**Comment by palazzef** [comment]
Yes, it worked. Thanks!
