### ISSUE TITLE
How was the moses VAE trained?

### ISSUE THREAD

**Issue by davidegraff** [GT4SD/gt4sd-core#192]
Hello!

I'm interested in using the Moses VAE generation code from GT4SD, but before then, I'd like to know how it was trained. I have a few assumptions based on inspecting the codebase, and I was hoping to have confirmed or corrected:

- trained on Zinc 250k with 80/20 train/val split
- KL is linearly ramped from 0 → 0.05 over 100 epochs
- all model hyperparameters use default values from [the config](https://github.com/GT4SD/moses/blob/main/moses/vae/config.py)

thanks for the help!

**Comment by jannisborn** [comment]
Hi @davidegraff,

Thx for your interest.

1. The VAE was trained on ~3M molecules from PubChem with 15k held-out samples for validation.
2. Correct, but the model was trained for ~55 epochs.
3. We used `gt4sd-trainer` to train the model like this:

```sh
gt4sd-trainer \
--training_pipeline_name moses-vae-trainer \
--train_load ${DATA_FOLDER}/pubchem_train.smi \
--val_load ${DATA_FOLDER}/pubchem_test.smi \
--test_smiles_filepath  \
--embedding_size 64 \
--q_cell gru \
--q_bidir True \
--q_d_h 256 \
--q_dropout 0.5 \
--d_cell gru \
--d_n_layers 3 \
--d_dropout 0.1 \
--d_d_h 512 \
--d_z 128 \
--freeze_embeddings False \
--grad_clipping 50 \
--kl_start 0 \
--kl_w_start 0 \
--kl_w_end 0.05 \
--lr_start 0.0003 \
--lr_n_period 7 \
--lr_n_restarts 4 \
--lr_n_mult 1 \
--lr_end 0.00003 \
--n_last 1000 \
--n_jobs 1 \
--n_workers 1 \
--save_frequency 100 \
--seed 0 \
--device cuda \
--log_file ${LOG_FOLDER}/log_train_moses_vae.txt \
--model_save ${MODEL_FOLDER}/model.pt \
--config_save ${MODEL_FOLDER}/config.pt \
--vocab_save ${MODEL_FOLDER}/vocab.pt
```

I hope this helps. Closing this but feel free to reopen if you need anything else.

**Comment by davidegraff** [comment]
where can I get the training data?

**Comment by davidegraff** [comment]
I'm guessing it's the [PubChemQC](https://pubs.acs.org/doi/10.1021/acs.jcim.7b00083) dataset based on the source code?

**Comment by jannisborn** [comment]
No it's not that one. The 3M molecules were randomly sampled from a 77M heavy dump of all of PubChem

**Comment by davidegraff** [comment]
where can I download this dataset? There are a bunch of pubchem versions out there, with the current one being ~250M so I'm not sure which version you're referring to. Sampling 3M from the current release would only have about 30% overlap with the molecules you trained on. Also, is it 3M samples exactly? Earlier, you mentioned "approximately" 3M samples

**Comment by jannisborn** [comment]
Just an addendum: The `.smi` was obtained from PubChem's FTP server: https://ftp.ncbi.nlm.nih.gov/pubchem/Compound/CURRENT-Full/SDF/

We converted the SDF to SMILES, then randomly selected 3M molecules, had to discard a few hundreds due to invalidity and from the remaining ones we put 15k aside for validation, the rest was used for training!

**Comment by jannisborn** [comment]
We just realized that under `Extras` you can also donwload the SMILES directly: https://ftp.ncbi.nlm.nih.gov/pubchem/Compound/Extras/

Currently it's >100M since PubChem grew a lot since we obtained the dump in May 2020 (which had 77M entries)
