### ISSUE TITLE
Is there a demo of "Multitask Text and Chemistry T5"?

### ISSUE THREAD

**Issue by HKQiu** [GT4SD/gt4sd-core#223]
Is there a demo of "Multitask Text and Chemistry T5"?
Including the demo of training data for fine-tuning, the demo of inference.

Best regards.

**Comment by jannisborn** [comment]
Hi @HKQiu,
Thanks for your interest! 
- There's a gradio demo where you can perform inference in the browser: https://huggingface.co/spaces/GT4SD/multitask-text-and-chemistry-t5
- The source code for the model is here: https://github.com/GT4SD/multitask_text_and_chemistry_t5 There's an example of training/finetuning the model which uses GT4SD via the `gt4sd-trainer` command.

Hope this helps!

**Comment by HKQiu** [comment]
> 

Thanks for help!
Have a nice day!

**Comment by medicine-wave** [comment]
I see, t5-small(finetuned) achieved 0.95 BLEU score in the paragraph2action task, can you provide more details?

**Comment by jannisborn** [comment]
The paragraph2actions task has been originally described in this paper: https://www.nature.com/articles/s41467-020-17266-6

**Comment by medicine-wave** [comment]
> The paragraph2actions task has been originally described in this paper: https://www.nature.com/articles/s41467-020-17266-6

Thanks, I knew the paper. I mean the training details of your work to achieve 0.95 BLEU. It's so fascinating!

**Comment by jannisborn** [comment]
Thanks :) The training process is detailed here: https://github.com/GT4SD/multitask_text_and_chemistry_t5/tree/main#model-training 

Note that it only includes a small subset of the data we used, however, the formatting of the sample data is exactly as you need it
