### ISSUE TITLE
Problem of Chem+Text T5

### ISSUE THREAD

**Issue by medicine-wave** [GT4SD/gt4sd-core#228]
Some questions about [Problem of the metrics in the paper](https://github.com/GT4SD/multitask_text_and_chemistry_t5/issues/1)
and [Problem of the finetuneing code and some training details](https://github.com/GT4SD/multitask_text_and_chemistry_t5/issues/2)?

**Comment by christofid** [comment]
Hi, thanks for your interest on GT4SD and Chem+Text T5 model. Let us answer these questions in the respective repo, so I am closing this issue for now.
