### ISSUE TITLE
Problem of  the weights of text-and-chemistry-t5-base-augm

### ISSUE THREAD

**Issue by Jenonone** [GT4SD/gt4sd-core#229]
I cannot reproduce the results of the paper through the weights on the huggingface repo:GT4SD/multitask-text-and-chemistry-t5-base-augm ,whose accuracy is supposed to 0.322,but I test it only to be 0.196.

**Comment by drugilsberg** [comment]
Thanks for checking out our work, I will close this issue and move it to the dedicated repo (https://github.com/GT4SD/multitask_text_and_chemistry_t5) and we will get back to you as soon as possible.

**Comment by drugilsberg** [comment]
New issue here: https://github.com/GT4SD/multitask_text_and_chemistry_t5/issues/3
