### ISSUE TITLE
Can't install the package with conda or from source

### ISSUE THREAD

**Issue by bransom960** [GT4SD/gt4sd-core#230]
Following the instructions in the documentation for the installation, the installation doesn't finish. 
When I try to build the package from source, the installation isn't able to function in a notebook.

I tried 3 different ways of installing
-------------------------
Using the conda installation in the documentation, after:
conda env create -f conda.yml 

I get this error:
ResolvePackageNotFound: 
 - pytorch-scatter[version='<=2.0.9']
 
Even though I have this package installed

-------------------------
when I run:
python setup.py install 

I get:
pkg_resources.extern.packaging.requirements.InvalidRequirement: .* suffix can only be used with `==` or `!=` operators
  torch (>=1.9.*)
----------------------
when I run:
python setup.py build
pip install gt4sd

It seems to make it through the installation, but then I get this error in the example jupyter notebooks:
File ~/anaconda3/lib/python3.10/site-packages/gt4sd/training_pipelines/moses/organ/core.py:32
     29 from dataclasses import dataclass, field
     30 from typing import Any, Dict
---> 32 from ..guacamol_baselines.moses_baselines.organ_train import main
     33 from moses.script_utils import MetricsReward
     35 from ...core import TrainingPipelineArguments
ModuleNotFoundError: No module named 'gt4sd.training_pipelines.moses.guacamol_baselines'

And I have tried to begin to go down the rabbit hole of updating various packages and installing them, but after adjusting a few scripts I stopped. 

**System (please complete the following information):**
 - Mac - M1 Chip
 - python: 3.8.12
 - pytorch-scatter: 2.0.9
 - pip: 19.1
 - GT4SD version: 1.3.2

**Comment by drugilsberg** [comment]
Hi @bransom960, unfortunately support for M1 is not yet there given issues with some does. We are tracking the issue here: https://github.com/GT4SD/gt4sd-core/issues/200.


The recommended solution is to use conda to install gt4sd in a x86 environment as described here: https://towardsdatascience.com/python-conda-environments-for-both-arm64-and-x86-64-on-m1-apple-silicon-147b943ffa55?gi=f8e4e3b2ece3.

Closing since it is a duplicate.
