### ISSUE TITLE
Phase Diagram Prediction from 'Prediction of Phase Diagrams and Associated Phase Structural Properties' paper

### ISSUE THREAD

**Issue by ander-db** [GT4SD/gt4sd-core#253]
**Is your feature request related to a problem? Please describe.**
I can't find the phase prediction model architecture referenced in the paper "Prediction of Phase Diagrams and Associated Phase Structural Properties" in either this repository or HuggingFace.

**Describe the solution you'd like**
Please indicate where the model architecture can be found, or if it's not available yet.

**Describe alternatives you've considered**
I've searched through the repository code and HuggingFace models.

**Additional context**
Referenced paper: https://pubs.acs.org/doi/10.1021/acs.iecr.2c00355

**Comment by jannisborn** [comment]
Closing as completed but feel free to re-open @ander-db
