### ISSUE TITLE
Installation on Linux for GPU usage

### ISSUE THREAD

**Issue by AsyaOrlova** [GT4SD/gt4sd-core#255]
Hello! I have a problem with creating environment for GPU usage. 

I run this command: 
`conda env create -f conda_gpu.yml`

And I get the error, which is depicted on the screenshots.
I suppose it is connected with pytorch-fast-transformers package.

**Screenshots**
![image](https://github.com/user-attachments/assets/399978f2-d957-41d6-bba0-8f8abbf4ebbf)
![image](https://github.com/user-attachments/assets/fcd017d5-cdfe-4f14-ab0c-60640c530165)

**System:**
 - OS: Linux
 - Python version: 3.10.13
 - GT4SD version: 1.4.3

**Comment by jannisborn** [comment]
HI @AsyaOrlova Thanks for your interest. Is this WSL? Because GT4SD does not support Windows

**Comment by AsyaOrlova** [comment]
@jannisborn Thanks for the quick answer! This is WSL, however I use it to connect to the remote server with Linux OS. So, I guess, this is not the problem, because I try to run gt4sd on server.

**Comment by jannisborn** [comment]
And you have GPU access on that machine? Otherwise you need [conda_cpu_linux.yml](https://github.com/GT4SD/gt4sd-core/blob/main/conda_cpu_linux.yml)

**Comment by AsyaOrlova** [comment]
Yes, I do have it. I also tried to create CPU environment and it failed with error as well.

**Comment by jannisborn** [comment]
Hard to debug from far, but your error suggests to pre-install torch into the env before attempting to install other deps

**Comment by AsyaOrlova** [comment]
I foun out I had problems specifically with gt4sd-molformer (something about a conflict between cuda and pytorch). So I created the environment without this package as a temporary workaround, since I don't actually need molformer for my purposes. Thank you for your help!

**Comment by jannisborn** [comment]
Closing as completed but feel free to reopn
