### ISSUE TITLE
gt4sd-trainer and pytoda error

### ISSUE THREAD

**Issue by georgosgeorgos** [GT4SD/gt4sd-core#80]
### Contributor License Agreement

- [X] I accept and sign the contributor license agreement ([CLA](../../CONTRIBUTING.md#contributor-license-agreement)) to contribute to GT4SD.

**Comment by jannisborn** [comment]
This problem is caused by side-effects from torchdrug: https://github.com/DeepGraphLearning/torchdrug/issues/96

It's unclear how it can be fixed, so we have to stall this until we hear from torchdrug developers
