### ISSUE TITLE
github workflow adding CLA is broken.

### ISSUE THREAD

**Issue by C-nit** [GT4SD/gt4sd-core#87]
CLA signing should be automatically committed via github actions, but the workflow fails to clone the repo it seems:

https://github.com/GT4SD/gt4sd-core/actions/runs/2488206057

**Comment by C-nit** [comment]
not sure if related: https://github.com/npm/npm/issues/6285#issuecomment-56640354

**Comment by drugilsberg** [comment]
@C-nit could very well be, I had to update it for the docs some time ago because it was causing the same issue: https://github.com/GT4SD/gt4sd-core/commit/b5a52659a7ca08ddc0eb17180798a7b347ee3950
